### ISSUE TITLE
Error creating project/workbook in CLI

### ISSUE THREAD

**Issue by jrothamel** [FlatFilers/platform-sdk-starter#48]
I am running into an issue creating a new project via the CLI. It appears to happen during the process of copying the starter kit repository from GitHub. Here's the error...

× Unable to clone starter repository
Error: Command failed: npx --yes degit FlatFilers/platform-sdk-starter#main panacea-flatfile-ndc
! could not fetch remote https://github.com/FlatFilers/platform-sdk-starter
! could not find commit hash for main

I am using Node v 16.13.2 on a Windows 10 PC. I ran the command via the PowerShell developer command prompt (as an admin). There doesn't appear to be any software blocking the execution of the command and I'm not being filtered from an Internet perspective. I'm not using a proxy.

**Comment by alnoorp** [comment]
@jrothamel can you please try the following commands to see if they work for you for cloning the repo?

- git clone git@github.com:FlatFilers/platform-sdk-starter.git
- git clone https://github.com/FlatFilers/platform-sdk-starter.git

**Comment by jrothamel** [comment]
The first command failed with the following error…

***@***.***

However, the second command seemed to work…

***@***.***

***@***.***

Jeff Rothamel
Manager, Software Engineering

T 651-424-4204
C 218-269-1912
www.panaceainc.com<https://www.panaceainc.com/>

***@***.***

Subscribe to Panacea Insights<https://insights.panaceainc.com/membership-join/membership-registration/>
Stay up to date on the latest in healthcare coding,
compliance, and reimbursement

***@***.***

*HFMA staff and volunteers determined that CDMauditor® – Hospital Zero-Base Pricing® and related modules have met certain criteria developed under the HFMA Peer Review Process. HFMA does not endorse or guarantee the use of this service.

**Comment by alnoorp** [comment]
@jrothamel I'm glad to hear the second command worked. Please let us know if you have any other issues.
