### ISSUE TITLE
Importing sample file produces error 'toLowerCase is not a function'

### ISSUE THREAD

**Issue by ashleygmulligan2** [FlatFilers/platform-sdk-starter#96]
To reproduce: 

Initialize a new project following the instructions on this page: 
https://flatfile.com/docs/get-started/quickstart/#initialize-a-project 

Using the command `npx flatfile publish ./examples/workbooks/FullExample.ts` to publish this example workbook. 

Import the `employees_sample.csv` against the Employees Portal that was created. 

Move from header selection to column matching and see it just hangs, and this error is produced in the console: 

![Image](https://user-images.githubusercontent.com/17680735/218503082-fcdfa678-908d-4b7c-aece-f7710821f136.png)

Reproduce Steps:

1. Create a new set of access key + secret key
2. Use the offered npx flatfile init command with included key and secret to download and install the platform SDK starter. 
3. cd into the project
4. use the suggested command npx flatfile publish ./examples/workbooks/FullExample.ts to deploy the example workbook
5. upload the employees_sample.csv file that comes in the project against the deployed Portal from the last step.
6. Confirm header selection, then review developer console. 

I've tested with various files and portals and this only seems to be happening with a combination of this file and this sheet. I can import this file against a different sheet/portal without an error, and I can import other sheets against this sheet without an error. I'm trying to recreate the file to provide this prospect with something to test but I haven't been able to get something working

To try to fix this file

- I've saved the file as an .xlsx file and get the same error
- I've copied the data into a new file and get the same error
- I've copied only specific columns (department, start date, bool) into another file that already had names and still got this error.

This will be an error anyone testing out the platform SDK will encounter. Several have reported already.

**Comment by alexhollenbeck** [comment]
Fixed by https://github.com/FlatFilers/platform-sdk-mono/pull/297 and https://github.com/FlatFilers/platform-sdk-starter/pull/98. Update existing projects to @flatfile/configure 0.5.13 or later to get the fix. New projects from npx flatfile init should have the fix.
